export enum TipoMovimiento {
  ENTRADA = 'ENTRADA',
  SALIDA = 'SALIDA',
  PRESTAMO = 'PRESTAMO',
  DEVOLUCION = 'DEVOLUCION',
  TRANSFERENCIA = 'TRANSFERENCIA',
}

export enum EstadoFisico {
  BUENO = 'BUENO',
  REGULAR = 'REGULAR',
  DANADO = 'DAÑADO',
  PERDIDO = 'PERDIDO',
}
