export enum TipoMovimiento {
  ENTRADA = 'ENTRADA',
  SALIDA = 'SALIDA',
  PRESTAMO = 'PRESTAMO',
  DEVOLUCION = 'DEVOLUCION',
  TRANSFERENCIA = 'TRANSFERENCIA',
}

export enum EstadoSolicitud {
  PENDIENTE = 'PENDIENTE',
  APROBADA = 'APROBADA',
  RECHAZADA = 'RECHAZADA',
  ENTREGADA = 'ENTREGADA',
  DEVUELTA = 'DEVUELTA',
}

export enum EstadoFisico {
  BUENO = 'BUENO',
  REGULAR = 'REGULAR',
  DANADO = 'DAÑADO',
  PERDIDO = 'PERDIDO',
}

export enum TipoSitio {
  BODEGA = 'BODEGA',
  AMBIENTE = 'AMBIENTE',
  LABORATORIO = 'LABORATORIO',
}
